"""Create tables

Revision ID: 5ca2ce493722
Revises: 
Create Date: 2023-05-15 05:42:20.614356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca2ce493722'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datafiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_jp', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('md5', sa.String(), nullable=True),
    sa.Column('dtype', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('litter_annual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('t1', sa.String(), nullable=True),
    sa.Column('t2', sa.String(), nullable=True),
    sa.Column('inst_period', sa.Integer(), nullable=True),
    sa.Column('n_collect', sa.Integer(), nullable=True),
    sa.Column('wdry_leaf', sa.Float(), nullable=True),
    sa.Column('wdry_branch', sa.Float(), nullable=True),
    sa.Column('wdry_rep', sa.Float(), nullable=True),
    sa.Column('wdry_all', sa.Float(), nullable=True),
    sa.Column('datafile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datafile_id'], ['datafiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('litter_each',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('t1', sa.String(), nullable=True),
    sa.Column('t2', sa.String(), nullable=True),
    sa.Column('inst_period', sa.Integer(), nullable=True),
    sa.Column('wdry_leaf', sa.Float(), nullable=True),
    sa.Column('wdry_branch', sa.Float(), nullable=True),
    sa.Column('wdry_rep', sa.Float(), nullable=True),
    sa.Column('wdry_all', sa.Float(), nullable=True),
    sa.Column('datafile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datafile_id'], ['datafiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seed_annual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('t1', sa.String(), nullable=True),
    sa.Column('t2', sa.String(), nullable=True),
    sa.Column('inst_period', sa.Integer(), nullable=True),
    sa.Column('species_jp', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('order', sa.String(), nullable=True),
    sa.Column('wdry', sa.Float(), nullable=True),
    sa.Column('number', sa.Float(), nullable=True),
    sa.Column('prop_viable', sa.Float(), nullable=True),
    sa.Column('datafile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datafile_id'], ['datafiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seed_each',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('t1', sa.String(), nullable=True),
    sa.Column('t2', sa.String(), nullable=True),
    sa.Column('inst_period', sa.Integer(), nullable=True),
    sa.Column('species_jp', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('order', sa.String(), nullable=True),
    sa.Column('wdry', sa.Float(), nullable=True),
    sa.Column('number', sa.Float(), nullable=True),
    sa.Column('prop_viable', sa.Float(), nullable=True),
    sa.Column('datafile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datafile_id'], ['datafiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tree_com_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Float(), nullable=True),
    sa.Column('mdate', sa.String(), nullable=True),
    sa.Column('nstem', sa.Float(), nullable=True),
    sa.Column('nsp', sa.Integer(), nullable=True),
    sa.Column('ba', sa.Float(), nullable=True),
    sa.Column('b', sa.Float(), nullable=True),
    sa.Column('shannon', sa.Float(), nullable=True),
    sa.Column('richness', sa.Float(), nullable=True),
    sa.Column('datafile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datafile_id'], ['datafiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tree_com_turnover',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t1', sa.Float(), nullable=True),
    sa.Column('t2', sa.Float(), nullable=True),
    sa.Column('n_m', sa.Float(), nullable=True),
    sa.Column('b_m', sa.Float(), nullable=True),
    sa.Column('r_rel', sa.Float(), nullable=True),
    sa.Column('m_rel', sa.Float(), nullable=True),
    sa.Column('p_rel', sa.Float(), nullable=True),
    sa.Column('l_rel', sa.Float(), nullable=True),
    sa.Column('r_abs', sa.Float(), nullable=True),
    sa.Column('m_abs', sa.Float(), nullable=True),
    sa.Column('p_abs', sa.Float(), nullable=True),
    sa.Column('l_abs', sa.Float(), nullable=True),
    sa.Column('datafile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datafile_id'], ['datafiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tree_sp_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Float(), nullable=True),
    sa.Column('species_jp', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('order', sa.String(), nullable=True),
    sa.Column('n', sa.Float(), nullable=True),
    sa.Column('ba', sa.Float(), nullable=True),
    sa.Column('b', sa.Float(), nullable=True),
    sa.Column('n_prop', sa.Float(), nullable=True),
    sa.Column('ba_prop', sa.Float(), nullable=True),
    sa.Column('b_prop', sa.Float(), nullable=True),
    sa.Column('datafile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datafile_id'], ['datafiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tree_sp_turnover',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t1', sa.Float(), nullable=True),
    sa.Column('t2', sa.Float(), nullable=True),
    sa.Column('species_jp', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('order', sa.String(), nullable=True),
    sa.Column('n_m', sa.Float(), nullable=True),
    sa.Column('b_m', sa.Float(), nullable=True),
    sa.Column('r_rel', sa.Float(), nullable=True),
    sa.Column('m_rel', sa.Float(), nullable=True),
    sa.Column('p_rel', sa.Float(), nullable=True),
    sa.Column('l_rel', sa.Float(), nullable=True),
    sa.Column('r_abs', sa.Float(), nullable=True),
    sa.Column('m_abs', sa.Float(), nullable=True),
    sa.Column('p_abs', sa.Float(), nullable=True),
    sa.Column('l_abs', sa.Float(), nullable=True),
    sa.Column('datafile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datafile_id'], ['datafiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tree_sp_turnover')
    op.drop_table('tree_sp_summary')
    op.drop_table('tree_com_turnover')
    op.drop_table('tree_com_summary')
    op.drop_table('seed_each')
    op.drop_table('seed_annual')
    op.drop_table('litter_each')
    op.drop_table('litter_annual')
    op.drop_table('datafiles')
    # ### end Alembic commands ###
